spring:
  jpa:
    show-sql: false
    hibernate:
      format_sql: true
      ddl-auto: update
      jdbc:
        time_zone: UTC
        dialect: MySQL8InnoDBDialect
  datasource:
      url: jdbc:mysql://localhost:{port}/{databaseName}?useLegacyDatetimeCode=false&serverTimezone=UTC
      username: {username}
      password: {password}
  database-platform: org.hibernate.dialect.MySQLDialect

---

